version: "3"

services:
  app:
    build: 
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    image: ${HUB_URL}${USER_NAME:-moyueheng}/${IMAGE_NAME:-codeserver-cuda12.2}:${IMAGE_TAG:-latest}
    volumes:
      - ./workspace:/workspace # 工作区备份
      - ./code-server/settings.json:/root/.local/share/code-server/User/settings.json # 工作区备份