version: "3"

services:
  app:
    build: 
      context: .
    ports:
      - "8081:8080"
    env_file:
      - .env
    image: ${HUB_URL}${USER_NAME:-moyueheng}/${IMAGE_NAME:-verl-codeserver}:${IMAGE_TAG:-latest}
    volumes:
      - ./workspace:/workspace/dev # 工作区备份
    